urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page
from django.views.generic.base import RedirectView
from django.views.static import serve

from tcof import views

urlpatterns = [
    url(r'home/$', cache_page(60 * 15)(views.home_method), name='home_url_name'),
    url(r'doc/$', cache_page(60 * 15)(views.doc_method), name='doc_url_name'),
    url(r'search/$', views.search_method, name='search_url_name'),
    url(r'browse/$', cache_page(60 * 15)(views.browse_method), name='browse_url_name'),
    url(r'ppi/$', views.ppi_method, name='ppi_url_name'),
    url(r'go/(?P<id>[A-Za-z0-9\-\:]+)$', cache_page(60 * 15)(views.go_method), name='go_url_name'),
    url(r'c6/(?P<idx>[A-Za-z0-9\-\:\_\.]+)$', cache_page(60 * 15)(views.c6_method), name='c6_url_name'),
    url(r'c7/(?P<idx>[A-Za-z0-9\-\:\_\.]+)$', cache_page(60 * 15)(views.c7_method), name='c7_url_name'),
    url(r'REACTOME/(?P<idx>[A-Za-z0-9\-\:\_\.]+)$', cache_page(60 * 15)(views.reactome_method), name='reactome_url_name'),
    url(r'KEGG/(?P<idx>[A-Za-z0-9\-\:\_\.]+)$', cache_page(60 * 15)(views.kegg_method), name='kegg_url_name'),
    url(r'gene/(?P<sym>[A-Za-z0-9\-]+)$', cache_page(60 * 15)(views.gene_method), name='gene_url_name'),
    url(r'disease/(?P<idx>[A-Za-z0-9\-\:\_\.]+)$', cache_page(60 * 15)(views.disease_method), name='disease_url_name'),
    
    # redirect non-matching urls to home/
    url(r'^.*$', RedirectView.as_view(url='home/', permanent=False), name='index'), 
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

templates/tcof/base.html
<!DOCTYPE html>
<html lang="en">
  
  <!--
      All js and css component should be in the DJANGO app 'static/tcof' folder
      Replace in the code below "tcof" with the appname
    -->

  {% load staticfiles %}

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<meta name="keywords" content="">
    
    <!-- FAVICON -->
    <link rel="shortcut icon" href="{% static 'tcof/images/favicon.ico' %}">
    
    <title>{% block title %}Home{% endblock %} // TcoF-DB</title>

    {% include 'tcof/stylesheets.html' %}
    {% include 'tcof/javascripts.html' %}
    
  </head>
  
  {% comment "Set app namespace" %}
  namepace 'tcof' needs declaration in main 'urls.py' not in apps local urls.py:
  urlpatterns = patterns('',
  url(r'^apps/tcof/', include('tcof.urls', namespace="tcof")),
  )
  {% endcomment %}
  
  {% url 'tcof:home_url_name' as home_url %}
  {% url 'tcof:contact_url_name' as contact %}
  {% url 'tcof:doc_url_name' as doc_url %}
  {% url 'tcof:search_url_name' as search %}
  {% url 'tcof:browse_url_name' as browse_url %}
  {% url 'tcof:gene_url_name' as gene %}
  {% url 'tcof:ppi_url_name' as ppi %}
  {% url 'tcof:go_url_name' as go_url %}
  {% url 'tcof:c7_url_name' as c7_url %}
  {% url 'tcof:c6_url_name' as c6_url %}

  <body>
    <div id="wrapper">
      
      <!-- Navigation -->
      {% include 'tcof/navigation.html' %}
      
      <!-- Page Content -->
      <div id="page-wrapper">
        <div class="container-fluid">
          {% comment %}
          BELOW GOES THE MAIN CONTENT FOR EACH INDIVIDUAL PAGE
          THE "block content" tag needs to be replaced in other templates.
          {% endcomment %}
          
          {% block content %}
          {% endblock %}

          <!-- Footer row -->
          <div class="row">
            <div class="col-lg-12 text-right">
              <hr>
              <p><a href="http://sschmeier.com"><i class="fa fa-home fa-fw"></i></a> // &copy; <a href="http://inms.massey.ac.nz">Massey University</a> & <a href="http://cbrc.kaust.edu.sa">CBRC@KAUST</a> 2010-2017 // v2.2.2</p>
            </div>
          </div>
          <!-- ./Footer row -->
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- /#page-wrapper -->
      
    </div>
    <!-- /#wrapper -->
  </body>
</html>

templates/tcof/browse_anno_base.html
{% extends "tcof/base.html" %}
{% block title %}Browse|{{ annotype }}{% endblock %}

{% load staticfiles %}

{% block content %}

<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header">Browse/search annotation terms: {{ annotype }}
      {% if annotypesub != '' %}
      ({{ annotypesub }})
      {% endif %}
    </h3>
       <!-- CONTENT -->
       
       <!-- spinner while loading -->
       <div id="loadingDiv">
         <img id="loading-image" src="{% static 'tcof/images/loading.gif' %}" width="24px" height="24px" alt="Loading..." />
       </div>
       <div id="contentDiv"></div>

       <!-- Load content into contentDiv with ajax-->
       <script language="javascript" type="text/javascript">
         var $loading = $('#loadingDiv').hide();
         $(document)
           .ajaxStart(function () {
             $loading.show();
           })
           .ajaxStop(function () {
             $loading.hide();
           });

         {% if annotypesub != '' %}
         $("#contentDiv").load("{{ browse_url }}?type=anno&atype={{ annotype }}:{{ annotypesub }}&content=1"); 
         {% else %}
         $("#contentDiv").load("{{ browse_url }}?type=anno&atype={{ annotype }}&content=1");
         {% endif %}

       </script>
        
       <!-- END OF CONTENT -->
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
{% endblock %}

templates/tcof/browse_enrich.html
{% extends "tcof/base.html" %}

{% block title %}ENRICH{% endblock %}

{% load staticfiles %}
{% block content %}

<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header">Enrich</h3>
    <div class="panel panel-default">
      <div class="panel-heading">
        <b>TcoFs</b><div style="float: right"><button title="Geneset enrichment analysis: Select genes by clicking on rows." type="button" id="button1" class="btn btn-default btn-xs">RUN GSEA</button></div>
      </div>
     <div class="panel-body">
       <div class="dataTable_wrapper">
         <table class="table table-condensed" id="example">
           
             <thead>
               <tr>
                 <th>Name</th>
                 <th>Position</th>
                 <th>Office</th>
                 <th>Age</th>
                 <th>Start date</th>
                 <th>Salary</th>
               </tr>
             </thead>
           
             <tbody>
               <tr>
                 <td><a href="http://google.com">Litaf</a></td>
                 <td>System Architect</td>
                 <td>Edinburgh</td>
                 <td>61</td>
                 <td>2011/04/25</td>
                 <td>$320,800</td>
               </tr>
               <tr>
                 <td>Adam17</td>
                 <td>Accountant</td>
                <td>Tokyo</td>
                 <td>63</td>
                 <td>2011/07/25</td>
                 <td>$170,750</td>
               </tr>
               <tr>
                 <td><a href="http://google.com">Map3k3</a></td>
                 <td>Junior Technical Author</td>
                 <td>San Francisco</td>
                 <td>66</td>
                 <td>2009/01/12</td>
                 <td>$86,000</td>
               </tr>
               <tr>
                 <td>Ripk1</td>
                 <td>Senior Javascript Developer</td>
                 <td>Edinburgh</td>
                 <td>22</td>
                 <td>2012/03/29</td>
                 <td>$433,060</td>
               </tr>
               <tr>
                 <td>Gata6</td>
                 <td>Accountant</td>
                 <td>Tokyo</td>
                 <td>33</td>
                 <td>2008/11/28</td>
                 <td>$162,700</td>
               </tr>
               <tr>
                 <td>Flot2</td>
                 <td>Integration Specialist</td>
                 <td>New York</td>
                 <td>61</td>
                 <td>2012/12/02</td>
                 <td>$372,000</td>
               </tr>
             </tbody>
           </table>
               <!-- DataTables JavaScript -->
         <script>
           $(document).ready( function() {
           var table = $('#example').DataTable( {
              responsive: true,
              "order": [[ 0, "asc" ]],
              "deferRender": true,
              responsive: true,
              lengthChange: false,
              "pageLength": 15,
              buttons: [ 'excel']
           } );
           table.buttons().container()
                     .appendTo( '#example_wrapper .col-sm-6:eq(0)' );

           $('#example tbody').on( 'click', 'tr', function () {
             $(this).toggleClass('selected');
           } );
           
           $('#button1').click( function () {
             var rows = table.rows('.selected').data();
             if (rows.length == 0) {
                 alert( "You need to select some genes to run GSEA" );
             } else {
                var genes = "";
                parser = new DOMParser();
                for (i = 0; i < rows.length; i++) {
                       // parse the gene out of the link
                       doc = parser.parseFromString(rows[i][0], "text/xml");
                       gene = doc.getElementsByTagName('a')[0].innerHTML
                       genes += gene + '\n';
               }
               enrich({list: [genes], popup: true, description: 'GSEA run with selected genes'});

               //alert( genes );
              //alert( table.rows('.selected').data().length +' row(s) selected' );
             }
           } );
           
           } ); // document ready
         </script>
   
       </div>
       <!-- /.table-responsive -->

       {% comment %}
        <a href="#" role='button' onclick="enrich({list: ['Litaf\nCdh1\nAdam17\nMap3k3\nArhgef1\nSdc4\nRipk1\nGata6\nVat1\nSrf\nMapk14\nLig3\nSlc4a7\nIcam1\nSgms1\nFst\nPlod2\nSrebf2\nAxin2\nCdc42\nGmcl1\nSpag9\nCdc42ep4\nS100a10\nRela\nE2f1\nTpd52l2\nTraf6\nDusp4\nPml\nTln1\nPpp1ca\nCnot4\nAdssl1\nGpr85\nCmtm6\nNfkb1\nIfrd2\nTollip\nXrcc6\nAsph\nTpm1\nTcf7l2\nPeli1\nDyrk2\nMmd\nSgk1\nSept10\nSkp2\nLdlrap1\nRbms1\nItgb1\nTom1l1\nDlk1\nMyd88\nPdpk1\nMap2k3\nPlcg2\nScarb1\nItpr3\nSpp1\nFoxa2\nSema3a\nFadd\nCdk6\nFlot2\nPbx3\nIqgap1'], popup: true, description: 'Targets (exp) of mmu-miR-124-3p'});"><button type="button" class="btn btn-default btn-xs">Run geneset enrichment analysis</button></a>
        {% endcomment %}
       
     </div>
    </div>


  

 </div>
 <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

{% endblock %}

templates/tcof/disease.html
{% extends "tcof/base.html" %}

{% block title %}Disease:{{ idx }}{% endblock %}

{% load staticfiles %}
{% block content %}

<div class="row">
  <div class="col-lg-12">
 
    <h3 class="page-header"><a title="Open at source" href="{{ url }}">Disease</a> - <small>{{ source }} : {{ term }} ({{ species  }})</small></h3>
    
    <!-- CONTENT -->
 
    <!-- spinner while loading -->
    <div id="loadingDiv">
      <img id="loading-image" src="{% static 'tcof/images/loading.gif' %}" width="24px" height="24px" alt="Loading..." />
    </div>
    <div id="contentDiv"></div>

    <!-- Load content into contentDiv with ajax-->
    <script language="javascript" type="text/javascript">
         var $loading = $('#loadingDiv').hide();
         $(document)
           .ajaxStart(function () {
             $loading.show();
           })
           .ajaxStop(function () {
             $loading.hide();
           });
 
         $("#contentDiv").load("{% url 'tcof:disease_url_name'  idx %}?content=1");
    </script>
    
    <!-- END OF CONTENT -->

    
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

{% endblock %}

templates/tcof/doc_base.html
{% extends "tcof/base.html" %}
{% block title %}Documentation{% endblock %}

{% load staticfiles %}
{% block content %}

<div class="row">
 <div class="col-lg-12">
   <h3 class="page-header"><i class="fa fa-info-circle"></i> Documentation</h3>
   
    <!-- CONTENT -->

    <!-- spinner while loading -->
    <div id="loadingDiv">
      <img id="loading-image" src="{% static 'tcof/images/loading.gif' %}" width="24px" height="24px" alt="Loading..." />
    </div>
    <div id="contentDiv"></div>

    <!-- Load content into contentDiv with ajax-->
    <script language="javascript" type="text/javascript">
         var $loading = $('#loadingDiv').hide();
         $(document)
           .ajaxStart(function () {
             $loading.show();
           })
           .ajaxStop(function () {
             $loading.hide();
           });
 
         $("#contentDiv").load("{{ doc_url }}?content=1");
    </script>
    
    <!-- END OF CONTENT -->
    
   
 </div>
 <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

{% endblock %}

templates/tcof/home_base.html
{% extends "tcof/base.html" %}
{% block title %}Home{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- Morris Charts CSS -->
<link href="{% static 'tcof/bower_components/morrisjs/morris.css' %}" rel="stylesheet">
<!-- Morris Charts JavaScript -->
<script src="{% static 'tcof/bower_components/raphael/raphael-min.js' %}"></script>
<script src="{% static 'tcof/bower_components/morrisjs/morris.min.js' %}"></script>

<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"><i class="fa fa-database"></i> TcoF-DB v2 // Database of transcription co-factors and transcription factor interactions</h3>
  </div>
</div>
<!-- /.row -->

<!-- CONTENT -->

<!-- spinner while loading -->
<div id="loadingDiv">
  <img id="loading-image" src="{% static 'tcof/images/loading.gif' %}" width="24px" height="24px" alt="Loading..." />
</div>
<div id="contentDiv"></div>

<!-- Load content into contentDiv with ajax-->
<script language="javascript" type="text/javascript">
      var $loading = $('#loadingDiv').hide();
         $(document)
           .ajaxStart(function () {
             $loading.show();
           })
           .ajaxStop(function () {
             $loading.hide();
           });
 
         $("#contentDiv").load("{{ home_url }}?content=1");
</script>

<!-- END OF CONTENT -->
{% endblock %}

templates/tcof/javascripts.html
{% load staticfiles %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script type="text/javascript" src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script type="text/javascript" src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <!-- JQERY -->
    <script src="{% static 'tcof/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'tcof/bower_components/bootstrap/dist/js/bootstrap.min.js' %}" async></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'tcof/bower_components/metisMenu/dist/metisMenu.min.js' %}" async></script>
    
    <!-- DataTables JavaScript -->
    <script src="{% static 'tcof/bower_components/datatables/media/js/jquery.dataTables.min.js' %}" defer></script>
    <script src="{% static 'tcof/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js' %}" defer></script>
    <!-- Datatables data download -->
    <script src="{% static 'tcof/dist/js/dataTables-additions/dataTables.buttons.min.js' %}" defer></script>
    <script src="{% static 'tcof/dist/js/dataTables-additions/buttons.bootstrap.min.js' %}" defer></script>
    <script src="{% static 'tcof/dist/js/dataTables-additions/jszip.min.js' %}" defer></script>
    <script src="{% static 'tcof/dist/js/dataTables-additions/buttons.html5.min.js' %}" defer></script>
    <script src="{% static 'tcof/dist/js/dataTables-additions/buttons.print.min.js' %}" defer></script>
    <!-- Datatables select -->
    <script src="{% static 'tcof/dist/js/dataTables-additions/dataTables.select.min.js' %}" defer></script>
    
    <!-- NEED TO BE LOADED LAST -->
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'tcof/dist/js/app.js' %}" defer></script>

templates/tcof/navigation.html
{% load staticfiles %}

      <!-- Navigation -->
      <nav class="navbar navbar-default navbar-static-top navbar-custom" role="navigation" style="margin-bottom: 0">
        
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ home_url }}"><img src="{% static 'tcof/images/logo.png' %}" style="height: 100%; width: auto;"></a>
        </div>
        <!-- /.navbar-header -->
        
        {% comment "Add search bar to the right in the navbar" %}
        <!-- navbar-top-right -->
        <div class="col-lg-2 pull-right">
          <form class="navbar-form" role="search" action="{{ search }}" method="GET">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search..." name="q" id="q" maxlength="50" required/>
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </form>
        </div>
        <!-- /.navbar-top-right -->
        {% endcomment %}
        
        <!-- NAVIGATION SIDEBAR -->
        <!-- Highlighting of the active class is handled by metisMenu -->
        <div class="navbar-default sidebar" role="navigation">
          <div class="sidebar-nav navbar-collapse">
            <!-- search bar -->
            <form class="navbar-form" role="search" action="{{ search }}" method="GET">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search..." name="q" id="q" maxlength="50" required/>
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                </div>
              </div>
            </form>
            <!-- ./serach bar -->
            <ul class="nav" id="side-menu">
              <li>
                <a href="{{ home_url }}"><i class="fa fa-home fa-fw"></i> Home</a>
              </li>
              <li>
                <a href="{{ doc_url }}"><i class="fa fa-info-circle fa-fw"></i> Documentation</a>
              </li>
              <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> TcoFs<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse"> <!-- added collapse for propper working nav third level-->
                  <li>
                    <a href="#">Human <span class="fa arrow"></span></a>
                    <ul class="nav nav-third-level">
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=human&class=all">All</a>
                      </li>
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=human&class=HC">High Conf</a>
                      </li>
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=human&class=1">Class 1</a>
                      </li>
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=human&class=2">Class 2</a>
                      </li>
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=human&class=3">Class 3</a>
                      </li>
                    </ul>
                    <!-- /.nav-third-level -->
                  </li>
		          <li>
                    <a href="#">Mouse <span class="fa arrow"></span></a>
                    <ul class="nav nav-third-level">
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=mouse&class=all">All</a>
                      </li>
		              <li>
                        <a href="{{ browse_url }}?type=tcof&species=mouse&class=HC">High Conf</a>
                      </li>
		              <li>
                        <a href="{{ browse_url }}?type=tcof&species=mouse&class=1">Class 1</a>
                      </li>
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=mouse&class=2">Class 2</a>
                      </li>
                      <li>
                        <a href="{{ browse_url }}?type=tcof&species=mouse&class=3">Class 3</a>
                      </li>
                    </ul>
                    <!-- /.nav-third-level -->
                  </li>
                </ul>
                <!-- /.nav-second-level -->
              </li>
              
	          <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> TFs<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
		          <li>
		            <a href="{{ browse_url }}?type=tf&species=human">Human</a>
		          </li>
		          <li>
		            <a href="{{ browse_url }}?type=tf&species=mouse">Mouse</a>
		          </li>
	            </ul>
              </li>
              
              <li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> TcoFs/TFs by annotation<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse"> <!-- added collapse for propper working nav third level-->

                  <li>
                    <a href="#">Gene Ontology <span class="fa arrow"></span></a>
                    <ul class="nav nav-third-level">
		              <li>
		                <a href="{{ browse_url }}?type=anno&atype=GO:Process">Process</a>
		              </li>
		              <li>
		                <a href="{{ browse_url }}?type=anno&atype=GO:Function">Function</a>
		              </li>
                    </ul>
                  </li>
                  <li>
                    <a href="#">Pathways <span class="fa arrow"></span></a>
                    <ul class="nav nav-third-level">
                      <li>
                        <a href="{{ browse_url }}?type=anno&atype=Pathways:KEGG">KEGG</a>
                      </li>
                      <li>
                        <a href="{{ browse_url }}?type=anno&atype=Pathways:REACTOME">REACTOME</a>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <a href="#">MSigDB <span class="fa arrow"></span></a>
                    <ul class="nav nav-third-level">
                      <li>
		                <a href="{{ browse_url }}?type=anno&atype=MSigDB:c6">Oncogenic sets (c6)</a>
		              </li>
                      <li>
		                <a href="{{ browse_url }}?type=anno&atype=MSigDB:c7">Immunological sets (c7)</a>
		              </li>
                    </ul>
                  </li>
                  <li>
		            <a href="{{ browse_url }}?type=anno&atype=Diseases">Diseases</a>
		          </li>
	            </ul><!-- /.nav-second-level -->
              </li>
              
            </ul> 
            
          </div>
          <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
      </nav>

templates/tcof/reactome.html
{% extends "tcof/base.html" %}

{% block title %}REACTOME:{{ idx }}{% endblock %}

{% load staticfiles %}
{% block content %}
<div class="row">
  <div class="col-lg-12">
 
    <h3 class="page-header"><a title="Open at pathway source" href="http://www.reactome.org/PathwayBrowser/#/{{ idx }}">REACTOME</a> - <small>{{ term }} ({{ species  }})</small></h3>
    <!-- CONTENT -->

    <!-- spinner while loading -->
    <div id="loadingDiv">
      <img id="loading-image" src="{% static 'tcof/images/loading.gif' %}" width="24px" height="24px" alt="Loading..." />
    </div>
    <div id="contentDiv"></div>

    <!-- Load content into contentDiv with ajax-->
    <script language="javascript" type="text/javascript">
         var $loading = $('#loadingDiv').hide();
         $(document)
           .ajaxStart(function () {
             $loading.show();
           })
           .ajaxStop(function () {
             $loading.hide();
           });
 
         $("#contentDiv").load("{% url 'tcof:reactome_url_name'  idx %}?content=1");
    </script>
    
    <!-- END OF CONTENT -->
    
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

{% endblock %}

templates/tcof/search.html
{% load staticfiles %}

   {% if search_results %}
     <div class="alert alert-info alert-dismissable">
       Query-term: <b>{{ search_term }}</b> <br>
       Number of results: {{ search_results|length }}
   {% else %}
       <div class="alert alert-info alert-danger">
       Query-term: <b>{{ search_term }}</b> <br>
       No results. Please try again.
   {% endif %}
      </div>
   
    {% if search_results|length > 0 %}
     <div class="panel panel-default">
       <div class="panel-body">
         <div class="dataTable_wrapper" width="100%">
           <table class="table  table-striped table-condensed" id="table1" width="100%">
             <thead>
               <tr>
                 <th></th>
                 <th>Symbol</th>
                 <th>Species</th>
                 <th>GeneID</th>
                 <th>Name</th>
                 <th>Alt.</th>
                 <th>UPid</th>
                 <th>UPacc</th>
                 <th>Type</th>
               </tr>
             </thead>
             <tbody>
               {% for e in search_results %}
               <tr>
                 <td><a title="Open gene in TcoF" href="{% url 'tcof:gene_url_name' e.1 %}"><i class="fa fa-arrow-circle-right"></i></a></td>
                 <td><a title="Open gene in TcoF" href="{% url 'tcof:gene_url_name' e.1 %}">{{ e.1 }}</a></td>
                 <td>{{ e.3 }}</td>
                 <td><a title="Open at NCBI Gene" href="https://www.ncbi.nlm.nih.gov/gene/{{ e.0 }}">{{ e.0 }}</a></td>
                 <td><a title="Open at NCBI Gene" href="https://www.ncbi.nlm.nih.gov/gene/{{ e.0 }}">{{ e.2 }}</a></td>
                 <td>{{ e.4 }}</td>
                 <td>
                   {% for up in e.6 %}
                   <a title="Open at Uniprot" href="http://www.uniprot.org/uniprot/{{ up.1 }}">{{ up.0 }}</a><br>
                   {% endfor %}
                 </td>
                 <td>
                   {% for up in e.6 %}
                   <a title="Open at Uniprot" href="http://www.uniprot.org/uniprot/{{ up.1 }}">{{ up.1 }}</a><br>
                   {% endfor %}
                 </td>
                 <td><b>{{ e.5 }}</b></td>
               </tr>
               {% endfor %}
             </tbody>
             
           </table>
           <!-- DataTables JavaScript -->
           <script>
             //var dataSet = {{ data|safe }};
         
             $(document).ready( function() {
             $('#table1').DataTable( {
               //"data": dataSet,
               "columns": [
                          {"width": "5px", "bSortable": false },
                          {"width": "100px"},
                          { "width": "65px" },
                          { "width": "65px" },
                          null,
                          { "width": "120px", "className": "text-left" },
                          { "width": "110px", "className": "text-left" },
                          { "width": "65px", "className": "text-left" },
                          { "width": "50px", "className": "text-center" }
               ],
               responsive: true,
               "order": [[ 1, "asc" ]],
               "deferRender": true
              } );
            } );
           </script>
   
         </div>
         <!-- /.table-responsive -->
       </div>
     </div>
     {% endif %}